export const INVESTOR_REPOSITORY = 'INVESTOR_REPOSITORY';
export const KYC_PROFILE_REPOSITORY = 'KYC_PROFILE_REPOSITORY';
export const BENEFICIAL_OWNER_REPOSITORY = 'BENEFICIAL_OWNER_REPOSITORY';
export const KYC_PROVIDER = 'KYC_PROVIDER';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';
