export const TENANT_REPOSITORY = 'TENANT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const IDENTITY_PROVIDER = 'IDENTITY_PROVIDER';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';
export const CLOCK = 'CLOCK';
export const IDEMPOTENCY_STORE = 'IDEMPOTENCY_STORE';
