export const OPPORTUNITY_REPOSITORY = 'OPPORTUNITY_REPOSITORY';
export const SCENARIO_MODEL_REPOSITORY = 'SCENARIO_MODEL_REPOSITORY';
export const INVESTMENT_THESIS_REPOSITORY = 'INVESTMENT_THESIS_REPOSITORY';
export const INVESTMENT_STRATEGY_REPOSITORY = 'INVESTMENT_STRATEGY_REPOSITORY';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';
