module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/apps', '<rootDir>/libs'],
  testMatch: ['**/*.spec.ts', '**/*.e2e-spec.ts'],
  transformIgnorePatterns: ['node_modules/(?!(?:@nestjs/typeorm)/)'],
  moduleNameMapper: {
    '^@nestjs/typeorm$': '<rootDir>/jest/stubs/nestjs-typeorm.js',
    '^@daos/shared-kernel/(.*)$': '<rootDir>/libs/shared-kernel/src/$1',
    '^@daos/shared-kernel$': '<rootDir>/libs/shared-kernel/src',
    '^@daos/identity-api/(.*)$': '<rootDir>/libs/identity-api/src/$1',
    '^@daos/identity-api$': '<rootDir>/libs/identity-api/src',
    '^@daos/investor-api/(.*)$': '<rootDir>/libs/investor-api/src/$1',
    '^@daos/investor-api$': '<rootDir>/libs/investor-api/src',
    '^@daos/asset-api/(.*)$': '<rootDir>/libs/asset-api/src/$1',
    '^@daos/asset-api$': '<rootDir>/libs/asset-api/src',
    '^@daos/opportunity-api/(.*)$': '<rootDir>/libs/opportunity-api/src/$1',
    '^@daos/opportunity-api$': '<rootDir>/libs/opportunity-api/src',
  },
  testTimeout: 30000,
  collectCoverageFrom: ['libs/**/src/**/*.ts', 'apps/**/src/domain/**/*.ts'],
};
