export const INVESTMENT_PRODUCT_REPOSITORY = 'INVESTMENT_PRODUCT_REPOSITORY';
export const SHARE_CLASS_REPOSITORY = 'SHARE_CLASS_REPOSITORY';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';
export const FEE_MODEL_CALCULATOR = 'FEE_MODEL_CALCULATOR';
export const MANDATE_RULE_ENGINE = 'MANDATE_RULE_ENGINE';
