export const WATERFALL_MODEL_REPOSITORY = Symbol('WATERFALL_MODEL_REPOSITORY');
export const DISTRIBUTION_REPOSITORY = Symbol('DISTRIBUTION_REPOSITORY');
export const CORPORATE_ACTION_REPOSITORY = Symbol('CORPORATE_ACTION_REPOSITORY');
export const OUTBOX_PUBLISHER = Symbol('OUTBOX_PUBLISHER');
