export const LEGAL_ENTITY_REPOSITORY = 'LEGAL_ENTITY_REPOSITORY';
export const CORPORATE_DOCUMENT_REPOSITORY = 'CORPORATE_DOCUMENT_REPOSITORY';
export const LEGAL_FORMATION_PROVIDER = 'LEGAL_FORMATION_PROVIDER';
export const ESIGNATURE_PROVIDER = 'ESIGNATURE_PROVIDER';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';