export const ISSUANCE_REPOSITORY = 'ISSUANCE_REPOSITORY';
export const MINT_REQUEST_REPOSITORY = 'MINT_REQUEST_REPOSITORY';
export const BLOCKCHAIN_GATEWAY = 'BLOCKCHAIN_GATEWAY';
export const TOKEN_STANDARD_PROVIDER = 'TOKEN_STANDARD_PROVIDER';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';