export const SETTLEMENT_REPOSITORY = Symbol('SETTLEMENT_REPOSITORY');
export const CUSTODY_REPOSITORY = Symbol('CUSTODY_REPOSITORY');
export const CUSTODIAN_BANK = Symbol('CUSTODIAN_BANK');
export const BLOCKCHAIN_SETTLEMENT = Symbol('BLOCKCHAIN_SETTLEMENT');
export const OUTBOX_PUBLISHER = Symbol('OUTBOX_PUBLISHER');
