export const PRICE_REPOSITORY = Symbol('PRICE_REPOSITORY');
export const VALUATION_MODEL_REPOSITORY = Symbol('VALUATION_MODEL_REPOSITORY');
export const PRICE_HISTORY_REPOSITORY = Symbol('PRICE_HISTORY_REPOSITORY');
export const PRICING_VENDOR_PORT = Symbol('PRICING_VENDOR_PORT');
export const VALUATION_AGENT_PORT = Symbol('VALUATION_AGENT_PORT');
export const OUTBOX_PUBLISHER = Symbol('OUTBOX_PUBLISHER');
