export const ASSET_REPOSITORY = 'ASSET_REPOSITORY';
export const DUE_DILIGENCE_REPORT_REPOSITORY = 'DUE_DILIGENCE_REPORT_REPOSITORY';
export const CASH_FLOW_MODEL_REPOSITORY = 'CASH_FLOW_MODEL_REPOSITORY';
export const VALUATION_ENGINE = 'VALUATION_ENGINE';
export const OUTBOX_PUBLISHER = 'OUTBOX_PUBLISHER';
export const ASSET_LIFECYCLE_HISTORY_REPOSITORY = 'ASSET_LIFECYCLE_HISTORY_REPOSITORY';
export const SPONSOR_REFERENCE_REPOSITORY = 'SPONSOR_REFERENCE_REPOSITORY';
