export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const ALLOCATION_REPOSITORY = Symbol('ALLOCATION_REPOSITORY');
export const CAPITAL_CALL_REPOSITORY = Symbol('CAPITAL_CALL_REPOSITORY');
export const CLOSING_REPOSITORY = Symbol('CLOSING_REPOSITORY');
export const PAYMENT_GATEWAY = Symbol('PAYMENT_GATEWAY');
export const ESCROW_PROVIDER = Symbol('ESCROW_PROVIDER');
export const OUTBOX_PUBLISHER = Symbol('OUTBOX_PUBLISHER');